use crate::error::{DatabaseError, DatabaseResult};
use crate::schema::DatabasePool;
use chrono::{DateTime, Utc};
use sqlx::Row;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MigrationInfo {
    pub version: i64,
    pub description: String,
    pub applied_at: DateTime<Utc>,
    pub success: bool,
    pub execution_time_ms: i64,
}

#[derive(Debug, Clone)]
pub struct RollbackPlan {
    pub migration_name: String,
    pub version: i64,
    pub reverse_sql: String,
    pub source: RollbackSource,
    pub is_safe: bool,
    pub warnings: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RollbackSource {
    AutoGenerated,
    DownFile,
}

#[derive(Debug, Clone)]
enum StmtKind {
    CreateTable { table: String },
    CreateIndex { index: String },
    AddColumn { table: String, column: String },
    CreateExtension,
    TransactionControl,
    Skip,
    Unsafe { reason: String },
}

pub async fn migration_status(pool: &DatabasePool) -> DatabaseResult<Vec<MigrationInfo>> {
    let result = sqlx::query(
        "SELECT version, description, installed_on, success, execution_time \
         FROM _sqlx_migrations ORDER BY version",
    )
    .fetch_all(pool.inner())
    .await;

    let rows = match result {
        Ok(rows) => rows,
        Err(e) if e.to_string().contains("does not exist") => return Ok(vec![]),
        Err(e) => {
            return Err(DatabaseError::MigrationError(format!(
                "Failed to query migration status: {}",
                e
            )));
        }
    };

    Ok(rows
        .iter()
        .map(|r| MigrationInfo {
            version: r.get("version"),
            description: r.get("description"),
            applied_at: r.get("installed_on"),
            success: r.get("success"),
            execution_time_ms: r.get("execution_time"),
        })
        .collect())
}

pub async fn rollback_last_migration(
    pool: &DatabasePool,
    migrations_dir: &Path,
) -> DatabaseResult<String> {
    let (version, description) = latest_migration(pool).await?;
    rollback_single(pool, migrations_dir, version, &description).await
}

pub async fn rollback_to_version(
    pool: &DatabasePool,
    migrations_dir: &Path,
    target_version: i64,
) -> DatabaseResult<Vec<String>> {
    let migrations = migrations_after(pool, target_version).await?;
    let mut rolled_back = Vec::new();
    for (version, description) in &migrations {
        let name = rollback_single(pool, migrations_dir, *version, description).await?;
        rolled_back.push(name);
    }
    Ok(rolled_back)
}

pub async fn dry_run_rollback(
    pool: &DatabasePool,
    migrations_dir: &Path,
    steps: Option<usize>,
) -> DatabaseResult<Vec<RollbackPlan>> {
    let all = all_applied_migrations(pool).await?;
    let to_check: Vec<_> = all.into_iter().take(steps.unwrap_or(1)).collect();
    let mut plans = Vec::new();
    for (version, description) in &to_check {
        let plan = plan_rollback(pool, migrations_dir, *version, description).await?;
        plans.push(plan);
    }
    Ok(plans)
}

async fn latest_migration(pool: &DatabasePool) -> DatabaseResult<(i64, String)> {
    let row = sqlx::query(
        "SELECT version, description FROM _sqlx_migrations \
         WHERE success = true ORDER BY version DESC LIMIT 1",
    )
    .fetch_optional(pool.inner())
    .await
    .map_err(|e| {
        if e.to_string().contains("does not exist") {
            DatabaseError::MigrationError("No migrations have been applied yet".to_string())
        } else {
            DatabaseError::MigrationError(format!("Failed to query migrations: {}", e))
        }
    })?;

    match row {
        Some(r) => Ok((r.get("version"), r.get("description"))),
        None => Err(DatabaseError::MigrationError(
            "No migrations to rollback".to_string(),
        )),
    }
}

async fn migrations_after(
    pool: &DatabasePool,
    target_version: i64,
) -> DatabaseResult<Vec<(i64, String)>> {
    let rows = sqlx::query(
        "SELECT version, description FROM _sqlx_migrations \
         WHERE success = true AND version > $1 ORDER BY version DESC",
    )
    .bind(target_version)
    .fetch_all(pool.inner())
    .await
    .map_err(|e| DatabaseError::MigrationError(format!("Failed to query migrations: {}", e)))?;

    let migrations: Vec<_> = rows
        .iter()
        .map(|r| (r.get("version"), r.get("description")))
        .collect();

    if migrations.is_empty() {
        return Err(DatabaseError::MigrationError(format!(
            "No applied migrations found after version {}",
            target_version
        )));
    }

    Ok(migrations)
}

async fn all_applied_migrations(pool: &DatabasePool) -> DatabaseResult<Vec<(i64, String)>> {
    let rows = sqlx::query(
        "SELECT version, description FROM _sqlx_migrations \
         WHERE success = true ORDER BY version DESC",
    )
    .fetch_all(pool.inner())
    .await
    .map_err(|e| {
        if e.to_string().contains("does not exist") {
            DatabaseError::MigrationError("No migrations have been applied yet".to_string())
        } else {
            DatabaseError::MigrationError(format!("Failed to query migrations: {}", e))
        }
    })?;

    Ok(rows
        .iter()
        .map(|r| (r.get("version"), r.get("description")))
        .collect())
}

fn migration_file(migrations_dir: &Path, version: i64, description: &str) -> PathBuf {
    migrations_dir.join(format!("{}_{}.sql", version, description))
}

fn down_file(migrations_dir: &Path, version: i64, description: &str) -> PathBuf {
    migrations_dir.join(format!("{}_{}.down.sql", version, description))
}

fn read_file(path: &Path) -> DatabaseResult<String> {
    std::fs::read_to_string(path).map_err(|e| {
        DatabaseError::MigrationError(format!(
            "Failed to read migration file {}: {}",
            path.display(),
            e
        ))
    })
}

async fn rollback_single(
    pool: &DatabasePool,
    migrations_dir: &Path,
    version: i64,
    description: &str,
) -> DatabaseResult<String> {
    let name = format!("{}_{}", version, description);

    let down_path = down_file(migrations_dir, version, description);
    if down_path.exists() {
        let sql = read_file(&down_path)?;
        execute_rollback(pool, version, &sql).await?;
        return Ok(name);
    }

    let sql = read_file(&migration_file(migrations_dir, version, description))?;
    let stmts = split_statements(&sql);
    let classified: Vec<StmtKind> = stmts.iter().map(|s| classify(s)).collect();
    let reverse = build_reverse_sql(pool, &classified).await?;
    execute_rollback(pool, version, &reverse).await?;
    Ok(name)
}

async fn plan_rollback(
    pool: &DatabasePool,
    migrations_dir: &Path,
    version: i64,
    description: &str,
) -> DatabaseResult<RollbackPlan> {
    let name = format!("{}_{}", version, description);

    let down_path = down_file(migrations_dir, version, description);
    if down_path.exists() {
        let sql = read_file(&down_path)?;
        return Ok(RollbackPlan {
            migration_name: name,
            version,
            reverse_sql: sql,
            source: RollbackSource::DownFile,
            is_safe: true,
            warnings: vec![],
        });
    }

    let up_path = migration_file(migrations_dir, version, description);
    let sql = read_file(&up_path)?;
    let stmts = split_statements(&sql);
    let classified: Vec<StmtKind> = stmts.iter().map(|s| classify(s)).collect();

    match build_reverse_sql(pool, &classified).await {
        Ok(reverse) => Ok(RollbackPlan {
            migration_name: name,
            version,
            reverse_sql: reverse,
            source: RollbackSource::AutoGenerated,
            is_safe: true,
            warnings: vec![],
        }),
        Err(e) => Ok(RollbackPlan {
            migration_name: name,
            version,
            reverse_sql: String::new(),
            source: RollbackSource::AutoGenerated,
            is_safe: false,
            warnings: vec![e.to_string()],
        }),
    }
}

async fn execute_rollback(
    pool: &DatabasePool,
    version: i64,
    reverse_sql: &str,
) -> DatabaseResult<()> {
    let mut tx = pool.begin().await?;

    for stmt in reverse_sql.split(';') {
        let trimmed = stmt.trim();
        if trimmed.is_empty() {
            continue;
        }
        sqlx::query(trimmed).execute(&mut *tx).await.map_err(|e| {
            DatabaseError::MigrationError(format!(
                "Rollback statement failed: {}\nStatement: {}",
                e, trimmed
            ))
        })?;
    }

    sqlx::query("DELETE FROM _sqlx_migrations WHERE version = $1")
        .bind(version)
        .execute(&mut *tx)
        .await
        .map_err(|e| {
            DatabaseError::MigrationError(format!(
                "Failed to remove migration record for version {}: {}",
                version, e
            ))
        })?;

    tx.commit()
        .await
        .map_err(|e| DatabaseError::TransactionError(e.to_string()))?;

    Ok(())
}

fn split_statements(sql: &str) -> Vec<String> {
    let mut stmts = Vec::new();
    let mut current = String::new();
    let mut in_single = false;
    let mut chars = sql.chars().peekable();

    while let Some(ch) = chars.next() {
        if in_single {
            current.push(ch);
            if ch == '\'' {
                if chars.peek() == Some(&'\'') {
                    current.push(chars.next().unwrap());
                } else {
                    in_single = false;
                }
            }
        } else {
            match ch {
                '\'' => {
                    in_single = true;
                    current.push(ch);
                }
                '-' if chars.peek() == Some(&'-') => {
                    chars.next();
                    while let Some(&c) = chars.peek() {
                        if c == '\n' {
                            break;
                        }
                        chars.next();
                    }
                }
                ';' => {
                    let trimmed = current.trim().to_string();
                    if !trimmed.is_empty() {
                        stmts.push(trimmed);
                    }
                    current = String::new();
                }
                _ => {
                    current.push(ch);
                }
            }
        }
    }

    let trimmed = current.trim().to_string();
    if !trimmed.is_empty() {
        stmts.push(trimmed);
    }

    stmts
}

fn classify(sql: &str) -> StmtKind {
    let trimmed = sql.trim();
    let upper = trimmed.to_ascii_uppercase();

    if upper == "BEGIN" || upper == "COMMIT" || upper.starts_with("COMMIT;") {
        return StmtKind::TransactionControl;
    }

    if upper.starts_with("CREATE EXTENSION") {
        return StmtKind::CreateExtension;
    }

    if upper.starts_with("DO $$") || upper.starts_with("DO $$ BEGIN") {
        return StmtKind::Skip;
    }

    if let Some(prefix_len) = upper
        .strip_prefix("CREATE TABLE IF NOT EXISTS ")
        .map(|_| "CREATE TABLE IF NOT EXISTS ".len())
        .or_else(|| {
            upper
                .strip_prefix("CREATE TABLE ")
                .map(|_| "CREATE TABLE ".len())
        })
    {
        let rest = &trimmed[prefix_len..];
        if let Some(table) = extract_identifier(rest) {
            return StmtKind::CreateTable { table };
        }
    }

    if upper.starts_with("CREATE UNIQUE INDEX") || upper.starts_with("CREATE INDEX") {
        let rest_orig = if upper.starts_with("CREATE UNIQUE INDEX IF NOT EXISTS") {
            &trimmed["CREATE UNIQUE INDEX IF NOT EXISTS ".len()..]
        } else if upper.starts_with("CREATE UNIQUE INDEX") {
            &trimmed["CREATE UNIQUE INDEX".len()..]
        } else if upper.starts_with("CREATE INDEX IF NOT EXISTS") {
            &trimmed["CREATE INDEX IF NOT EXISTS ".len()..]
        } else {
            &trimmed["CREATE INDEX".len()..]
        };
        if let Some(on_pos) = rest_orig.to_ascii_uppercase().find(" ON ") {
            let index_part = &rest_orig[..on_pos];
            if let Some(index) = extract_identifier(index_part.trim()) {
                return StmtKind::CreateIndex { index };
            }
        }
    }

    if let Some(rest_upper) = upper.strip_prefix("ALTER TABLE ") {
        let rest_orig = &trimmed["ALTER TABLE ".len()..];
        let tokens_upper: Vec<&str> = rest_upper.split_whitespace().collect();
        if tokens_upper.len() >= 4 {
            let table = extract_identifier(rest_orig).unwrap_or_default();
            let action = tokens_upper[1];

            match action {
                "ADD"
                    if tokens_upper.len() >= 4
                        && tokens_upper.get(2).copied() == Some("COLUMN") =>
                {
                    let has_if_not_exists = tokens_upper.get(3).copied() == Some("IF")
                        && tokens_upper.get(4).copied() == Some("NOT")
                        && tokens_upper.get(5).copied() == Some("EXISTS");
                    let col = if has_if_not_exists {
                        let after_column = &rest_orig[rest_upper
                            .to_ascii_uppercase()
                            .find("COLUMN ")
                            .unwrap_or(0)
                            + "COLUMN ".len()..];
                        let after_if_not = after_column
                            .find("IF NOT EXISTS ")
                            .map(|i| &after_column[i + "IF NOT EXISTS ".len()..])
                            .unwrap_or(after_column);
                        extract_identifier(after_if_not).unwrap_or_default()
                    } else {
                        let col_pos = rest_upper.to_ascii_uppercase().find("COLUMN ").unwrap_or(0)
                            + "COLUMN ".len();
                        extract_identifier(&rest_orig[col_pos..]).unwrap_or_default()
                    };
                    return StmtKind::AddColumn { table, column: col };
                }
                "DROP" => {
                    let sub = tokens_upper.get(2).copied().unwrap_or("");
                    let name = if sub == "COLUMN" || sub == "CONSTRAINT" {
                        let kw_pos = rest_upper.to_ascii_uppercase().find(sub).unwrap_or(0);
                        extract_identifier(&rest_orig[kw_pos + sub.len()..])
                            .unwrap_or_else(|| "?".to_string())
                    } else {
                        "?".to_string()
                    };
                    let reason = if sub == "COLUMN" {
                        format!(
                            "DROP COLUMN {} on table {} is data-destructive",
                            name, table
                        )
                    } else if sub == "CONSTRAINT" {
                        format!(
                            "DROP CONSTRAINT {} on table {} cannot be auto-reversed",
                            name, table
                        )
                    } else {
                        format!(
                            "ALTER TABLE {} DROP operation cannot be auto-reversed",
                            table
                        )
                    };
                    return StmtKind::Unsafe { reason };
                }
                "ALTER" if tokens_upper.get(2).copied() == Some("COLUMN") => {
                    let col_pos = rest_upper.find("COLUMN ").unwrap_or(0) + "COLUMN ".len();
                    let col = extract_identifier(&rest_orig[col_pos..]).unwrap_or_default();
                    let remaining = &tokens_upper[4..];
                    let reason = if remaining.first().copied() == Some("SET") {
                        let next = remaining.get(1).copied().unwrap_or("");
                        if next == "DATA" {
                            format!(
                                "ALTER COLUMN {} SET DATA TYPE on table {} may lose data",
                                col, table
                            )
                        } else if next == "NOT" {
                            format!(
                                "ALTER COLUMN {} SET NOT NULL on table {} may fail if data has NULLs",
                                col, table
                            )
                        } else {
                            format!(
                                "ALTER COLUMN {} on table {} requires manual rollback",
                                col, table
                            )
                        }
                    } else {
                        format!(
                            "ALTER COLUMN {} on table {} requires manual rollback",
                            col, table
                        )
                    };
                    return StmtKind::Unsafe { reason };
                }
                "RENAME" => {
                    return StmtKind::Unsafe {
                        reason: format!(
                            "RENAME operation on table {} requires manual rollback",
                            table
                        ),
                    };
                }
                _ => {}
            }
        }
    }

    if upper.starts_with("DROP TABLE") {
        return StmtKind::Unsafe {
            reason: "DROP TABLE is data-destructive and cannot be rolled back".to_string(),
        };
    }

    if upper.starts_with("DROP INDEX") {
        return StmtKind::Unsafe {
            reason: "DROP INDEX cannot be auto-rolled back".to_string(),
        };
    }

    if upper.starts_with("DELETE ") {
        return StmtKind::Unsafe {
            reason: "DELETE is data-destructive and cannot be rolled back".to_string(),
        };
    }

    if upper.starts_with("UPDATE ") {
        return StmtKind::Unsafe {
            reason: "UPDATE is data-destructive and cannot be rolled back".to_string(),
        };
    }

    if upper.starts_with("INSERT ") {
        return StmtKind::Unsafe {
            reason: "INSERT is data-destructive and cannot be rolled back".to_string(),
        };
    }

    if upper.starts_with("TRUNCATE ") {
        return StmtKind::Unsafe {
            reason: "TRUNCATE is data-destructive and cannot be rolled back".to_string(),
        };
    }

    StmtKind::Skip
}

fn extract_identifier(s: &str) -> Option<String> {
    let trimmed = s.trim();
    if trimmed.is_empty() {
        return None;
    }
    if let Some(inner) = trimmed.strip_prefix('"') {
        if let Some(end) = inner.find('"') {
            return Some(inner[..end].to_string());
        }
    }
    Some(
        trimmed
            .split_whitespace()
            .next()?
            .trim_end_matches('(')
            .to_string(),
    )
}

async fn is_table_empty(pool: &DatabasePool, table: &str) -> DatabaseResult<bool> {
    let quoted = if table.starts_with('"') {
        table.to_string()
    } else {
        format!("\"{}\"", table)
    };
    let query = format!("SELECT COUNT(*) FROM {}", quoted);
    let row: (i64,) = sqlx::query_as(&query)
        .fetch_one(pool.inner())
        .await
        .map_err(|e| {
            DatabaseError::MigrationError(format!(
                "Failed to check if table {} is empty: {}",
                table, e
            ))
        })?;
    Ok(row.0 == 0)
}

async fn build_reverse_sql(pool: &DatabasePool, stmts: &[StmtKind]) -> DatabaseResult<String> {
    let mut reverse = Vec::new();

    for stmt in stmts {
        match stmt {
            StmtKind::CreateTable { table } => {
                let empty = is_table_empty(pool, table).await?;
                if !empty {
                    return Err(DatabaseError::MigrationError(format!(
                        "Cannot auto-rollback CREATE TABLE {}: table is not empty. \
                         Create a .down.sql file for manual rollback.",
                        table
                    )));
                }
                reverse.push(format!("DROP TABLE IF EXISTS {}", table));
            }
            StmtKind::CreateIndex { index } => {
                reverse.push(format!("DROP INDEX IF EXISTS {}", index));
            }
            StmtKind::AddColumn { table, column } => {
                let empty = is_table_empty(pool, table).await?;
                if !empty {
                    return Err(DatabaseError::MigrationError(format!(
                        "Cannot auto-rollback ADD COLUMN {}.{}: table has data. \
                         Create a .down.sql file for manual rollback.",
                        table, column
                    )));
                }
                reverse.push(format!(
                    "ALTER TABLE {} DROP COLUMN IF EXISTS {}",
                    table, column
                ));
            }
            StmtKind::Unsafe { reason } => {
                return Err(DatabaseError::MigrationError(format!(
                    "{}. Create a .down.sql file for manual rollback.",
                    reason
                )));
            }
            StmtKind::CreateExtension | StmtKind::TransactionControl | StmtKind::Skip => {}
        }
    }

    if reverse.is_empty() {
        return Err(DatabaseError::MigrationError(
            "No rollbackable statements found in migration. \
             Create a .down.sql file if rollback is needed."
                .to_string(),
        ));
    }

    Ok(reverse.join(";\n") + ";")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_split_statements_simple() {
        let sql = "BEGIN;\nCREATE TABLE foo (id INT);\nCOMMIT;";
        let stmts = split_statements(sql);
        assert_eq!(stmts.len(), 3);
        assert_eq!(stmts[0], "BEGIN");
        assert_eq!(stmts[1], "CREATE TABLE foo (id INT)");
        assert_eq!(stmts[2], "COMMIT");
    }

    #[test]
    fn test_split_statements_with_strings() {
        let sql = "ALTER TABLE t ADD COLUMN c TEXT DEFAULT 'hello;world';";
        let stmts = split_statements(sql);
        assert_eq!(stmts.len(), 1);
        assert!(stmts[0].contains("'hello;world'"));
    }

    #[test]
    fn test_split_statements_with_escaped_quotes() {
        let sql = "INSERT INTO t (c) VALUES ('it''s a test');";
        let stmts = split_statements(sql);
        assert_eq!(stmts.len(), 1);
        assert!(stmts[0].contains("'it''s a test'"));
    }

    #[test]
    fn test_split_statements_with_comments() {
        let sql = "-- comment\nCREATE TABLE foo (id INT);\n-- another comment";
        let stmts = split_statements(sql);
        assert_eq!(stmts.len(), 1);
        assert_eq!(stmts[0], "CREATE TABLE foo (id INT)");
    }

    #[test]
    fn test_split_statements_no_semicolons() {
        let sql = "SELECT 1";
        let stmts = split_statements(sql);
        assert_eq!(stmts.len(), 1);
        assert_eq!(stmts[0], "SELECT 1");
    }

    #[test]
    fn test_classify_create_table() {
        let sql = "CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY)";
        let kind = classify(sql);
        match kind {
            StmtKind::CreateTable { table } => assert_eq!(table, "users"),
            other => panic!("Expected CreateTable, got {:?}", other),
        }
    }

    #[test]
    fn test_classify_create_table_no_if_not_exists() {
        let sql = "CREATE TABLE users (id UUID PRIMARY KEY)";
        let kind = classify(sql);
        match kind {
            StmtKind::CreateTable { table } => assert_eq!(table, "users"),
            other => panic!("Expected CreateTable, got {:?}", other),
        }
    }

    #[test]
    fn test_classify_create_index() {
        let sql = "CREATE INDEX IF NOT EXISTS idx_users_email ON users(email)";
        let kind = classify(sql);
        match kind {
            StmtKind::CreateIndex { index } => assert_eq!(index, "idx_users_email"),
            other => panic!("Expected CreateIndex, got {:?}", other),
        }
    }

    #[test]
    fn test_classify_create_unique_index() {
        let sql = "CREATE UNIQUE INDEX IF NOT EXISTS idx_unique ON users(email)";
        let kind = classify(sql);
        match kind {
            StmtKind::CreateIndex { index } => assert_eq!(index, "idx_unique"),
            other => panic!("Expected CreateIndex, got {:?}", other),
        }
    }

    #[test]
    fn test_classify_add_column() {
        let sql = "ALTER TABLE users ADD COLUMN avatar_url TEXT";
        let kind = classify(sql);
        match kind {
            StmtKind::AddColumn { table, column } => {
                assert_eq!(table, "users");
                assert_eq!(column, "avatar_url");
            }
            other => panic!("Expected AddColumn, got {:?}", other),
        }
    }

    #[test]
    fn test_classify_add_column_if_not_exists() {
        let sql = "ALTER TABLE search_index ADD COLUMN IF NOT EXISTS content_type TEXT NOT NULL DEFAULT ''";
        let kind = classify(sql);
        match kind {
            StmtKind::AddColumn { table, column } => {
                assert_eq!(table, "search_index");
                assert_eq!(column, "content_type");
            }
            other => panic!("Expected AddColumn, got {:?}", other),
        }
    }

    #[test]
    fn test_classify_drop_constraint() {
        let sql = "ALTER TABLE documents DROP CONSTRAINT IF EXISTS documents_author_id_fkey";
        let kind = classify(sql);
        match kind {
            StmtKind::Unsafe { reason } => {
                assert!(reason.contains("DROP CONSTRAINT"));
            }
            other => panic!("Expected Unsafe, got {:?}", other),
        }
    }

    #[test]
    fn test_classify_drop_column() {
        let sql = "ALTER TABLE search_index DROP COLUMN IF EXISTS title";
        let kind = classify(sql);
        match kind {
            StmtKind::Unsafe { reason } => {
                assert!(reason.contains("DROP COLUMN"));
            }
            other => panic!("Expected Unsafe, got {:?}", other),
        }
    }

    #[test]
    fn test_classify_alter_column_type() {
        let sql = "ALTER TABLE documents ALTER COLUMN tags SET DATA TYPE JSONB USING tags::jsonb";
        let kind = classify(sql);
        match kind {
            StmtKind::Unsafe { reason } => {
                assert!(reason.contains("SET DATA TYPE"));
            }
            other => panic!("Expected Unsafe, got {:?}", other),
        }
    }

    #[test]
    fn test_classify_drop_table() {
        let sql = "DROP TABLE IF EXISTS old_table";
        let kind = classify(sql);
        assert!(matches!(kind, StmtKind::Unsafe { .. }));
    }

    #[test]
    fn test_classify_drop_index() {
        let sql = "DROP INDEX IF EXISTS idx_old";
        let kind = classify(sql);
        assert!(matches!(kind, StmtKind::Unsafe { .. }));
    }

    #[test]
    fn test_classify_delete() {
        let sql = "DELETE FROM users WHERE is_active = false";
        let kind = classify(sql);
        match kind {
            StmtKind::Unsafe { reason } => {
                assert!(reason.contains("DELETE"));
            }
            other => panic!("Expected Unsafe, got {:?}", other),
        }
    }

    #[test]
    fn test_classify_update() {
        let sql = "UPDATE users SET role = 'viewer' WHERE role = 'admin'";
        let kind = classify(sql);
        match kind {
            StmtKind::Unsafe { reason } => {
                assert!(reason.contains("UPDATE"));
            }
            other => panic!("Expected Unsafe, got {:?}", other),
        }
    }

    #[test]
    fn test_classify_insert() {
        let sql = "INSERT INTO users (id, name) VALUES ('1', 'test')";
        let kind = classify(sql);
        match kind {
            StmtKind::Unsafe { reason } => {
                assert!(reason.contains("INSERT"));
            }
            other => panic!("Expected Unsafe, got {:?}", other),
        }
    }

    #[test]
    fn test_classify_begin_commit() {
        assert!(matches!(classify("BEGIN"), StmtKind::TransactionControl));
        assert!(matches!(classify("COMMIT"), StmtKind::TransactionControl));
    }

    #[test]
    fn test_classify_create_extension() {
        let sql = "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"";
        assert!(matches!(classify(sql), StmtKind::CreateExtension));
    }

    #[test]
    fn test_classify_do_block() {
        let sql = "DO $$ BEGIN CREATE EXTENSION IF NOT EXISTS \"pgcrypto\"; EXCEPTION WHEN duplicate_object THEN NULL; END $$";
        assert!(matches!(classify(sql), StmtKind::Skip));
    }

    #[test]
    fn test_classify_rename() {
        let sql = "ALTER TABLE old_name RENAME TO new_name";
        let kind = classify(sql);
        assert!(matches!(kind, StmtKind::Unsafe { .. }));
    }

    #[test]
    fn test_classify_set_not_null() {
        let sql = "ALTER TABLE search_index ALTER COLUMN content_type SET NOT NULL";
        let kind = classify(sql);
        assert!(matches!(kind, StmtKind::Unsafe { .. }));
    }

    #[test]
    fn test_classify_quoted_table() {
        let sql = "CREATE TABLE IF NOT EXISTS \"my-table\" (id UUID PRIMARY KEY)";
        let kind = classify(sql);
        match kind {
            StmtKind::CreateTable { table } => assert_eq!(table, "my-table"),
            other => panic!("Expected CreateTable, got {:?}", other),
        }
    }

    #[test]
    fn test_extract_identifier_unquoted() {
        assert_eq!(extract_identifier("users ("), Some("users".to_string()));
        assert_eq!(extract_identifier("users"), Some("users".to_string()));
    }

    #[test]
    fn test_extract_identifier_quoted() {
        assert_eq!(
            extract_identifier("\"my-table\" (id INT)"),
            Some("my-table".to_string())
        );
    }

    #[test]
    fn test_extract_identifier_empty() {
        assert_eq!(extract_identifier(""), None);
    }

    #[test]
    fn test_migration_file_path() {
        let dir = Path::new("/migrations");
        let path = migration_file(dir, 20260327000000, "initial_schema");
        assert_eq!(
            path,
            PathBuf::from("/migrations/20260327000000_initial_schema.sql")
        );
    }

    #[test]
    fn test_down_file_path() {
        let dir = Path::new("/migrations");
        let path = down_file(dir, 20260327000000, "initial_schema");
        assert_eq!(
            path,
            PathBuf::from("/migrations/20260327000000_initial_schema.down.sql")
        );
    }

    #[test]
    fn test_complex_migration_detected() {
        let sql = r#"
BEGIN;
ALTER TABLE documents DROP CONSTRAINT IF EXISTS documents_author_id_fkey;
ALTER TABLE documents ALTER COLUMN tags SET DATA TYPE JSONB USING tags::jsonb;
ALTER TABLE search_index DROP COLUMN IF EXISTS title;
COMMIT;
"#;
        let stmts = split_statements(sql);
        let classified: Vec<StmtKind> = stmts.iter().map(|s| classify(s)).collect();

        let has_unsafe = classified
            .iter()
            .any(|s| matches!(s, StmtKind::Unsafe { .. }));
        assert!(
            has_unsafe,
            "Complex migration with ALTER TYPE, DROP CONSTRAINT, DROP COLUMN should be detected as unsafe"
        );
    }

    #[test]
    fn test_safe_index_only_migration() {
        let sql = r#"
CREATE INDEX IF NOT EXISTS idx_sessions_user_status_activity
    ON sessions(user_id, status, last_activity DESC);
CREATE INDEX IF NOT EXISTS idx_team_members_team_user
    ON team_members(team_id, user_id);
"#;
        let stmts = split_statements(sql);
        let classified: Vec<StmtKind> = stmts.iter().map(|s| classify(s)).collect();

        let has_unsafe = classified
            .iter()
            .any(|s| matches!(s, StmtKind::Unsafe { .. }));
        assert!(
            !has_unsafe,
            "Index-only migration should be safe to auto-rollback"
        );

        let index_count = classified
            .iter()
            .filter(|s| matches!(s, StmtKind::CreateIndex { .. }))
            .count();
        assert_eq!(index_count, 2);
    }

    #[test]
    fn test_mixed_safe_unsafe() {
        let sql = r#"
BEGIN;
CREATE TABLE IF NOT EXISTS new_table (id UUID PRIMARY KEY);
CREATE INDEX IF NOT EXISTS idx_new ON new_table(id);
ALTER TABLE existing ALTER COLUMN type SET DATA TYPE TEXT;
COMMIT;
"#;
        let stmts = split_statements(sql);
        let classified: Vec<StmtKind> = stmts.iter().map(|s| classify(s)).collect();

        assert!(
            classified
                .iter()
                .any(|s| matches!(s, StmtKind::CreateTable { .. }))
        );
        assert!(
            classified
                .iter()
                .any(|s| matches!(s, StmtKind::CreateIndex { .. }))
        );
        assert!(
            classified
                .iter()
                .any(|s| matches!(s, StmtKind::Unsafe { .. }))
        );
    }

    #[test]
    fn test_create_table_with_schema() {
        let sql = "CREATE TABLE IF NOT EXISTS public.my_table (id UUID PRIMARY KEY)";
        let kind = classify(sql);
        match kind {
            StmtKind::CreateTable { table } => assert_eq!(table, "public.my_table"),
            other => panic!("Expected CreateTable, got {:?}", other),
        }
    }
}
