// Pages module - all application pages

pub mod admin;
pub mod audit;
pub mod billing;
pub mod catalog;
pub mod dashboard;
pub mod documents;
pub mod graph;
pub mod home;
pub mod login;
pub mod onboarding;
pub mod plugins;
pub mod profile;
pub mod register;
pub mod search;
pub mod settings;
pub mod spaces;
pub mod ssg;
pub mod tags;
pub mod teams;
pub mod templates;

pub use admin::roles::RolesPage;
pub use audit::AuditPage;
pub use billing::BillingPage;
pub use catalog::CatalogPage;
pub use dashboard::DashboardPage;
pub use documents::{DocumentEditPage, DocumentPage, DocumentsPage};
pub use graph::GraphPage;
pub use home::HomePage;
pub use login::LoginPage;
pub use onboarding::OnboardingPage;
pub use plugins::PluginsPage;
pub use profile::ProfilePage;
pub use register::RegisterPage;
pub use search::SearchPage;
pub use settings::SettingsPage;
pub use spaces::SpacesPage;
pub use ssg::SsgPage;
pub use tags::TagsPage;
pub use teams::TeamDetailPage;
pub use teams::TeamsPage;
pub use templates::TemplatesPage;
