// OpenAPI Documentation Module
// Provides OpenAPI specification generation and Swagger UI

use std::sync::OnceLock;
use utoipa::OpenApi;
use utoipa::openapi::OpenApi as OpenApiSpec;
use utoipa_swagger_ui::SwaggerUi;

/// Compute the OpenAPI spec once and cache it. The utoipa derive macro
/// expands to deeply nested types; `OnceLock` avoids recomputation.
pub(crate) fn openapi_spec() -> &'static OpenApiSpec {
    static SPEC: OnceLock<OpenApiSpec> = OnceLock::new();
    SPEC.get_or_init(ApiDoc::openapi)
}

// Import all route types for documentation

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Tachyon API",
        version = "1.0.0",
        description = "Tachyon Knowledge Management System API\n\nA comprehensive API for managing documents, knowledge graphs, projects, and collaborative workflows.",
        terms_of_service = "https://tachyon.local/terms",
        contact(
            name = "Tachyon Support",
            email = "support@tachyon.local"
        ),
        license(
            name = "Apache-2.0",
            url = "https://opensource.org/licenses/Apache-2.0"
        )
    ),
    servers(
        (url = "http://localhost:8080", description = "Development server"),
        (url = "http://localhost:8080/api/v1", description = "API v1 endpoint")
    ),
    tags(
        (name = "documents", description = "Document management endpoints"),
        (name = "search", description = "Search endpoints"),
        (name = "users", description = "User management endpoints"),
        (name = "spaces", description = "Space management endpoints"),
        (name = "templates", description = "Document template endpoints"),
        (name = "versions", description = "Document version management"),
        (name = "attachments", description = "Document attachment endpoints"),
        (name = "rendering", description = "Content rendering endpoints"),
        (name = "auth", description = "Authentication endpoints"),
        (name = "sessions", description = "Session management endpoints"),
        (name = "projects", description = "Project/Service catalog endpoints"),
        (name = "components", description = "Component catalog endpoints"),
        (name = "nodes", description = "Knowledge graph node endpoints"),
        (name = "edges", description = "Knowledge graph edge endpoints"),
        (name = "graph", description = "Graph query endpoints"),
        (name = "repositories", description = "Repository management endpoints"),
        (name = "teams", description = "Team management endpoints"),
        (name = "roles", description = "Role management endpoints"),
        (name = "reviews", description = "Document review endpoints"),
        (name = "activity", description = "Activity feed endpoints"),
        (name = "notifications", description = "Notification endpoints"),
        (name = "webhooks", description = "Webhook management endpoints"),
        (name = "plugins", description = "Plugin management endpoints"),
        (name = "onboarding", description = "User onboarding endpoints"),
        (name = "collaboration", description = "Collaboration endpoints"),
        (name = "billing", description = "Billing and subscription endpoints"),
        (name = "organizations", description = "Organization management endpoints"),
        (name = "system", description = "System health and metrics endpoints"),
        (name = "files", description = "File management endpoints"),
        (name = "ssg", description = "Static site generation endpoints"),
        (name = "analytics", description = "Admin analytics and dashboard endpoints"),
        (name = "admin", description = "Admin-only endpoints"),
    ),
    paths(
        crate::routes::document::document_crud::list_documents,
        crate::routes::document::document_crud::list_documents_cursor,
        crate::routes::document::document_crud::create_document,
        crate::routes::document::document_crud::get_document,
        crate::routes::document::document_crud::update_document,
        crate::routes::document::document_crud::delete_document,
        crate::routes::document::document_crud::get_document_metadata,
        crate::routes::document::document_crud::render_markdown,
        crate::routes::document::document_batch::batch_operations,
        crate::routes::document::document_search::search_documents,
        crate::routes::document::document_search::get_backlinks,
        crate::routes::document::document_attachments::list_attachments,
        crate::routes::document::document_attachments::upload_attachment,
        crate::routes::document::document_attachments::download_attachment,
        crate::routes::document::document_attachments::delete_attachment,
        crate::routes::document::document_templates::list_templates,
        crate::routes::document::document_templates::get_template,
        crate::routes::document::document_templates::create_template,
        crate::routes::document::document_templates::update_template,
        crate::routes::document::document_templates::delete_template,
        crate::routes::document::document_versions::list_versions,
        crate::routes::document::document_versions::get_version,
        crate::routes::document::document_versions::create_version,
        crate::routes::document::document_versions::diff_versions,
        crate::routes::search::search,
        crate::routes::search::global_search,
        crate::routes::search::reindex_tantivy,
        crate::routes::search::suggest,
        crate::routes::search::create_saved_search,
        crate::routes::search::list_saved_searches,
        crate::routes::search::get_saved_search,
        crate::routes::search::update_saved_search,
        crate::routes::search::delete_saved_search,
        crate::routes::user::list_users,
        crate::routes::user::create_user,
        crate::routes::user::get_user,
        crate::routes::user::update_user,
        crate::routes::user::delete_user,
        crate::routes::user::get_me,
        crate::routes::user::handlers::register,
        crate::routes::user::handlers::authenticate,
        crate::routes::user::handlers::refresh_token_handler,
        crate::routes::user::handlers::guest_login,
        crate::routes::user::handlers::auth_status,
        crate::routes::user::handlers::logout,
        crate::routes::user::handlers::guest_status,
        crate::routes::user::handlers::update_me,
        crate::routes::space::list_spaces,
        crate::routes::space::create_space,
        crate::routes::space::get_space,
        crate::routes::space::update_space,
        crate::routes::space::delete_space,
        crate::routes::session::create_session,
        crate::routes::session::get_session,
        crate::routes::session::validate_session,
        crate::routes::session::revoke_session,
        crate::routes::session::list_sessions,
        crate::routes::session::revoke_all_sessions,
        crate::routes::tags::list_tags,
        crate::routes::notification::list_notifications,
        crate::routes::notification::unread_count,
        crate::routes::notification::mark_notification_read,
        crate::routes::notification::mark_all_read,
        crate::routes::conflict::get_conflict_info,
        crate::routes::conflict::resolve_conflict,
        crate::routes::review::create_review,
        crate::routes::review::update_review,
        crate::routes::review::list_reviews,
        crate::routes::role::list_roles,
        crate::routes::role::create_role,
        crate::routes::role::get_role,
        crate::routes::role::update_role,
        crate::routes::role::delete_role,
        crate::routes::role::seed_default_roles,
        crate::routes::team::list_teams,
        crate::routes::team::create_team,
        crate::routes::team::get_team,
        crate::routes::team::update_team,
        crate::routes::team::delete_team,
        crate::routes::team::list_team_members,
        crate::routes::team::add_team_member,
        crate::routes::team::update_team_member,
        crate::routes::team::remove_team_member,
        crate::routes::repository::init_repository,
        crate::routes::repository::clone_repository,
        crate::routes::repository::commit,
        crate::routes::repository::push,
        crate::routes::repository::status,
        crate::routes::repository::list_repositories,
        crate::routes::repository::get_repository,
        crate::routes::repository::delete_repository,
        crate::routes::node::create_node,
        crate::routes::node::get_node,
        crate::routes::node::update_node,
        crate::routes::node::delete_node,
        crate::routes::node::list_nodes,
        crate::routes::node::create_edge,
        crate::routes::node::get_node_edges,
        crate::routes::node::delete_edge,
        crate::routes::node::query_graph,
        crate::routes::node::get_graph_stats,
        crate::routes::node::get_graph_at_time,
        crate::routes::node::get_graph_diff,
        crate::routes::activity::list_activity,
        crate::routes::activity::create_activity,
        crate::routes::catalog::create_project,
        crate::routes::catalog::list_projects,
        crate::routes::catalog::get_project,
        crate::routes::catalog::get_project_by_slug,
        crate::routes::catalog::update_project,
        crate::routes::catalog::delete_project,
        crate::routes::catalog::create_component,
        crate::routes::catalog::get_component,
        crate::routes::catalog::list_project_components,
        crate::routes::catalog::delete_component,
        crate::routes::catalog::add_project_member,
        crate::routes::catalog::list_project_members,
        crate::routes::catalog::remove_project_member,
        crate::routes::catalog::get_catalog_stats,
        crate::routes::webhook::create_webhook,
        crate::routes::webhook::list_webhooks,
        crate::routes::webhook::delete_webhook,
        crate::routes::plugin::list_plugins,
        crate::routes::plugin::get_plugin,
        crate::routes::plugin::create_plugin,
        crate::routes::plugin::update_plugin,
        crate::routes::plugin::delete_plugin,
        crate::routes::plugin::invoke_hook,
        crate::routes::onboarding::get_onboarding_status,
        crate::routes::onboarding::complete_step,
        crate::routes::onboarding::create_sample_content,
        crate::routes::onboarding::get_suggestions,
        crate::routes::collaboration::update_presence,
        crate::routes::collaboration::get_presence,
        crate::routes::collaboration::remove_presence,
        crate::routes::collaboration::list_comments,
        crate::routes::collaboration::create_comment,
        crate::routes::collaboration::update_comment,
        crate::routes::collaboration::delete_comment,
        crate::routes::collaboration::get_mentions,
        crate::routes::ecosystem::api_info,
        crate::routes::ecosystem::get_notification_preferences,
        crate::routes::ecosystem::update_notification_preferences,
        crate::routes::ecosystem::get_webhook_logs,
        crate::routes::billing::handlers::list_plans,
        crate::routes::billing::handlers::create_subscription,
        crate::routes::billing::handlers::get_subscription,
        crate::routes::billing::handlers::list_invoices,
        crate::routes::billing::handlers::get_usage,
        crate::routes::billing::handlers::change_plan,
        crate::routes::billing::handlers::cancel_subscription,
        crate::routes::billing::handlers::create_mandate,
        crate::routes::billing::handlers::get_mandate_status,
        crate::routes::billing::handlers::create_payment,
        crate::routes::billing::handlers::get_payment_status,
        crate::routes::billing::handlers::webhook_handler,
        crate::routes::organization::list_organizations,
        crate::routes::organization::get_organization,
        crate::routes::organization::create_organization,
        crate::routes::organization::update_organization,
        crate::routes::organization::delete_organization,
        crate::routes::organization::list_members,
        crate::routes::organization::add_member,
        crate::routes::organization::update_member,
        crate::routes::organization::remove_member,
        crate::routes::password_reset::request_password_reset,
        crate::routes::password_reset::confirm_password_reset,
        crate::routes::password_reset::request_email_verification,
        crate::routes::password_reset::confirm_email_verification,
        crate::routes::magic_link::request_magic_link,
        crate::routes::magic_link::verify_magic_link,
        crate::routes::sms_otp::request_sms_otp,
        crate::routes::sms_otp::verify_sms_otp,
        crate::routes::files::list_directory,
        crate::routes::files::read_file,
        crate::routes::files::search_files,
        crate::routes::files::get_tree,
        crate::routes::files::get_stats,
        crate::routes::files::get_recent_files,
        crate::routes::files::upload_file,
        crate::routes::mfa::enable_mfa,
        crate::routes::mfa::verify_mfa,
        crate::routes::mfa::disable_mfa,
        crate::routes::mfa::mfa_authenticate,
        crate::routes::ssg::get_ssg_config,
        crate::routes::ssg::build_site,
        crate::routes::ssg::download_site,
        crate::routes::oauth2::google_authorize,
        crate::routes::oauth2::google_callback,
        crate::routes::oauth2::github_authorize,
        crate::routes::oauth2::github_callback,
        crate::routes::analytics::get_overview,
        crate::routes::analytics::get_document_activity,
        crate::routes::analytics::get_user_activity,
        crate::routes::analytics::get_search_activity,
        crate::routes::analytics::get_api_activity,
        crate::routes::signup::signup,
        crate::routes::query_stats::query_stats_handler,
    ),
    components(schemas(
        tachyon_database::types::DocumentMetadata,
        tachyon_database::types::RepositoryMetadata,
        tachyon_database::types::SessionRecord,
        tachyon_database::types::Project,
        tachyon_database::types::ProjectMember,
        tachyon_database::types::Component,
        tachyon_database::Space,
        tachyon_database::UserRecord,
        crate::routes::document::DocumentResponse,
        crate::routes::document::DocumentSearchResponse,
        crate::routes::document::DocumentCursorPage,
        crate::pagination::Cursor,
        crate::routes::document::document_crud::CreateDocumentRequest,
        crate::routes::document::document_crud::UpdateDocumentRequest,
        crate::routes::document::document_batch::BatchRequest,
        crate::routes::document::document_batch::BatchResponse,
        crate::routes::document::document_batch::BatchOperation,
        crate::routes::document::document_batch::BatchAction,
        crate::routes::document::document_batch::BatchOperationResult,
        crate::routes::document::document_batch::BatchOperationStatus,
        crate::routes::document::document_search::BacklinksResponse,
        crate::routes::document::document_search::BacklinkItem,
        crate::routes::document::document_attachments::AttachmentResponse,
        crate::routes::document::document_templates::TemplateResponse,
        crate::routes::document::document_templates::CreateTemplateBody,
        crate::routes::document::document_templates::UpdateTemplateBody,
        crate::routes::document::document_versions::VersionResponse,
        crate::routes::document::document_versions::CreateVersionBody,
        crate::routes::document::document_versions::DiffLine,
        crate::routes::document::document_versions::DocumentDiffResponse,
        crate::routes::document::document_versions::DiffStats,
        crate::routes::search::SearchResultsResponse,
        crate::routes::search::SearchResultItem,
        crate::routes::search::SearchFacetsResponse,
        crate::routes::search::FacetItem,
        crate::routes::search::GlobalSearchResultsResponse,
        crate::routes::search::ProjectSearchResultItem,
        crate::routes::search::SavedSearchResponse,
        crate::routes::search::CreateSavedSearchBody,
        crate::routes::search::UpdateSavedSearchBody,
        crate::routes::user::UserResponse,
        crate::routes::user::UserListResponse,
        crate::routes::user::CreateUserRequest,
        crate::routes::user::UpdateUserRequest,
        crate::routes::user::types::RegisterRequest,
        crate::routes::user::types::UpdateProfileRequest,
        crate::routes::user::types::AuthenticateRequest,
        crate::routes::user::types::AuthenticateResponse,
        crate::routes::user::types::RefreshRequest,
        crate::routes::user::types::LogoutRequest,
        crate::routes::user::types::UserErrorResponse,
        crate::routes::space::SpaceResponse,
        crate::routes::space::CreateSpaceBody,
        crate::routes::space::UpdateSpaceBody,
        crate::routes::session::CreateSessionRequest,
        crate::routes::session::SessionResponse,
        crate::routes::session::SessionListResponse,
        crate::routes::session::SessionListResponse,
        crate::routes::tags::TagInfo,
        crate::routes::tags::TagsResponse,
        crate::routes::notification::NotificationListResponse,
        crate::routes::notification::NotificationCursorPage,
        crate::routes::notification::UnreadCountResponse,
        crate::routes::notification::MarkReadResponse,
        crate::routes::notification::MarkAllReadResponse,
        crate::routes::conflict::ResolveConflictRequest,
        crate::routes::conflict::ConflictInfo,
        crate::routes::conflict::MergeResultInfo,
        crate::routes::review::ReviewResponse,
        crate::routes::role::RoleResponse,
        crate::routes::role::CreateRoleRequest,
        crate::routes::role::UpdateRoleRequest,
        crate::routes::team::TeamResponse,
        crate::routes::team::CreateTeamRequest,
        crate::routes::team::UpdateTeamRequest,
        crate::routes::team::TeamMemberResponse,
        crate::routes::repository::RepositoryResponse,
        crate::routes::repository::RepositoryStatus,
        crate::routes::repository::RepositoryListResponse,
        crate::routes::repository::InitRepositoryRequest,
        crate::routes::repository::CloneRepositoryRequest,
        crate::routes::repository::CommitRequest,
        crate::routes::repository::PushRequest,
        crate::routes::node::CreateNodeRequest,
        crate::routes::node::UpdateNodeRequest,
        crate::routes::node::CreateEdgeRequest,
        crate::routes::node::GraphQueryRequest,
        crate::routes::node::NodeListResponse,
        crate::routes::node::EdgeListResponse,
        crate::routes::node::GraphQueryResponse,
        crate::routes::activity::ActivityListResponse,
        crate::routes::activity::ActivityCursorPage,
        crate::routes::catalog::AddMemberRequest,
        crate::routes::plugin::PluginResponse,
        crate::routes::plugin::CreatePluginBody,
        crate::routes::plugin::UpdatePluginBody,
        crate::routes::plugin::InvokeHookRequest,
        crate::routes::plugin::InvokeHookResponse,
        crate::routes::onboarding::OnboardingStatusResponse,
        crate::routes::onboarding::CompleteStepRequest,
        crate::routes::onboarding::CompleteStepResponse,
        crate::routes::onboarding::SampleContentResponse,
        crate::routes::onboarding::SuggestionsResponse,
        crate::routes::onboarding::TemplateSuggestion,
        crate::routes::collaboration::PresenceInfo,
        crate::routes::collaboration::PresenceStatus,
        crate::routes::collaboration::CursorInfo,
        crate::routes::collaboration::Comment,
        crate::routes::collaboration::CommentStatus,
        crate::routes::collaboration::CommentAnchor,
        crate::routes::collaboration::UpdatePresenceRequest,
        crate::routes::collaboration::PresenceResponse,
        crate::routes::collaboration::CreateCommentRequest,
        crate::routes::collaboration::UpdateCommentRequest,
        crate::routes::collaboration::CommentsResponse,
        crate::routes::collaboration::MentionsResponse,
        crate::routes::collaboration::MentionNotification,
        crate::routes::ecosystem::ApiInfo,
        crate::routes::ecosystem::FeatureFlag,
        crate::routes::ecosystem::UpdateNotificationPrefRequest,
        crate::routes::ecosystem::NotificationPrefsResponse,
        crate::routes::ecosystem::WebhookEventFilter,
        crate::routes::ecosystem::WebhookDeliveryLog,
        crate::routes::ecosystem::WebhookDeliveryStatus,
        crate::routes::ecosystem::WebhookLogsResponse,
        crate::routes::billing::Plan,
        crate::routes::billing::UsageMetrics,
        crate::routes::billing::CreateSubscriptionRequest,
        crate::routes::billing::SubscriptionResponse,
        crate::routes::billing::PlanDetails,
        crate::routes::billing::PlansResponse,
        crate::routes::billing::PlanInfo,
        crate::routes::billing::InvoicesResponse,
        crate::routes::billing::UsageResponse,
        crate::routes::billing::CreateMandateRequest,
        crate::routes::billing::MandateResponse,
        crate::routes::billing::MandateStatusResponse,
        crate::routes::billing::CreatePaymentRequest,
        crate::routes::billing::PaymentResponse,
        crate::routes::billing::PaymentStatusResponse,
        crate::routes::billing::ChangePlanRequest,
        crate::routes::billing::ChangePlanResponse,
        crate::routes::billing::WebhookPayload,
        crate::routes::organization::OrganizationResponse,
        crate::routes::organization::OrganizationMemberResponse,
        crate::routes::organization::CreateOrganizationBody,
        crate::routes::organization::UpdateOrganizationBody,
        crate::routes::organization::AddMemberBody,
        crate::routes::organization::UpdateMemberBody,
        crate::routes::password_reset::PasswordResetRequest,
        crate::routes::password_reset::PasswordResetConfirm,
        crate::routes::password_reset::EmailVerifyRequest,
        crate::routes::password_reset::EmailVerifyConfirm,
        crate::routes::password_reset::MessageResponse,
        crate::routes::sms_otp::SmsOtpMessageResponse,
        crate::routes::sms_otp::SmsOtpRequest,
        crate::routes::sms_otp::SmsOtpVerify,
        crate::routes::files::ListResponse,
        crate::routes::files::EntryInfo,
        crate::routes::files::ReadResponse,
        crate::routes::files::SearchResponse,
        crate::routes::files::SearchResultEntry,
        crate::routes::files::TreeResponse,
        crate::routes::files::StatsResponse,
        crate::routes::files::LargestFileEntry,
        crate::routes::files::RecentResponse,
        crate::routes::files::RecentFileEntry,
        crate::routes::files::UploadResponse,
        crate::routes::mfa::MfaEnableResponse,
        crate::routes::mfa::MfaVerifyRequest,
        crate::routes::mfa::MfaDisableRequest,
        crate::routes::mfa::MfaAuthRequest,
        crate::routes::ssg::SsgConfigResponse,
        crate::routes::ssg::SsgBuildRequest,
        crate::routes::ssg::SsgBuildResponse,
        crate::routes::ssg::SsgBuildResultWrapper,
        crate::routes::ssg::SsgNavLink,
        crate::error::ErrorResponse,
        crate::routes::analytics::AnalyticsOverview,
        crate::routes::analytics::DailyActivity,
        crate::routes::analytics::DailyActivityResponse,
        crate::routes::analytics::DailyUserActivity,
        crate::routes::analytics::UserActivityResponse,
        crate::routes::analytics::DailySearchCount,
        crate::routes::analytics::SearchActivityResponse,
        crate::routes::analytics::ApiRequestVolume,
        crate::routes::analytics::ApiActivityResponse,
        crate::routes::signup::SignupRequest,
        crate::routes::signup::SignupResponse,
        crate::routes::signup::SignupErrorResponse,
        crate::routes::query_stats::QueryStatsResponse,
    )),
    modifiers(&SecurityAddon)
)]
pub struct ApiDoc;

struct SecurityAddon;

impl utoipa::Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "bearer_auth",
                utoipa::openapi::security::SecurityScheme::Http(
                    utoipa::openapi::security::Http::new(
                        utoipa::openapi::security::HttpAuthScheme::Bearer,
                    ),
                ),
            );
            components.add_security_scheme(
                "api_key",
                utoipa::openapi::security::SecurityScheme::ApiKey(
                    utoipa::openapi::security::ApiKey::Header(
                        utoipa::openapi::security::ApiKeyValue::new("X-API-Key"),
                    ),
                ),
            );
            // Manual schema for TreeNode (self-referential, cannot use derive ToSchema)
            // Defined as raw JSON Schema inserted into the components map
            let tree_node_json: serde_json::Value = serde_json::json!({
                "type": "object",
                "properties": {
                    "name": { "type": "string" },
                    "path": { "type": "string" },
                    "is_dir": { "type": "boolean" },
                    "children": {
                        "type": "array",
                        "items": { "$ref": "#/components/schemas/TreeNode" }
                    }
                }
            });
            let tree_node_schema: utoipa::openapi::schema::Schema =
                serde_json::from_value(tree_node_json).expect("TreeNode schema must be valid");
            components.schemas.insert(
                "TreeNode".into(),
                utoipa::openapi::RefOr::T(tree_node_schema),
            );
        }
    }
}

/// Create Swagger UI instance for merging into router
pub fn create_swagger_ui() -> SwaggerUi {
    SwaggerUi::new("/api/docs").url("/api/docs/openapi.json", openapi_spec().clone())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_openapi_spec_generation() {
        let spec = openapi_spec();
        let json = spec.to_pretty_json().expect("Failed to generate JSON");
        assert!(json.contains("Tachyon API"));
        assert!(json.contains("documents"));
        assert!(json.contains("users"));
        assert!(json.contains("auth"));
    }

    #[test]
    fn test_openapi_spec_has_security_schemes() {
        let spec = openapi_spec();
        let json = spec.to_pretty_json().expect("Failed to generate JSON");
        assert!(json.contains("bearer_auth"));
        assert!(json.contains("api_key"));
    }

    #[test]
    fn test_openapi_spec_has_all_tags() {
        let spec = openapi_spec();
        let json = spec.to_pretty_json().expect("Failed to generate JSON");
        assert!(json.contains("documents"));
        assert!(json.contains("users"));
        assert!(json.contains("auth"));
        assert!(json.contains("sessions"));
        assert!(json.contains("nodes"));
        assert!(json.contains("repositories"));
        assert!(json.contains("projects"));
    }
}
