// SEO routes: robots.txt, sitemap.xml, and server-side rendered document pages

use axum::{
    extract::{Path, State},
    http::{header, StatusCode},
    response::{Html, IntoResponse},
    Extension,
};
use tachyon_core::DocumentId;
use tachyon_database::{DatabasePool, DocumentRepository};
use tachyon_renderer::{
    context::{AuthorInfo, RenderContext, RenderMetadata},
    page::{render_full_page, SiteConfig as RendererSiteConfig},
    RenderConfig, Renderer,
};

/// Shared state for SEO routes
#[derive(Clone)]
pub struct SeoState {
    pub pool: DatabasePool,
    pub site_config: crate::config::SiteConfig,
}

/// Generate robots.txt
pub async fn robots_txt(State(state): State<SeoState>) -> impl IntoResponse {
    let base_url = state.site_config.base_url.trim_end_matches('/');

    let body = format!(
        r#"# robots.txt for {site_title}
# Generated by Tachyon

User-agent: *
Allow: /
Disallow: /api/
Disallow: /ws

# Sitemap
Sitemap: {base_url}/sitemap.xml

# Crawl-delay (respectful to our servers)
Crawl-delay: 1
"#,
        site_title = state.site_config.title,
        base_url = base_url,
    );

    (
        StatusCode::OK,
        [(header::CONTENT_TYPE, "text/plain; charset=utf-8")],
        body,
    )
}

/// Generate sitemap.xml dynamically from the document catalog
pub async fn sitemap_xml(State(state): State<SeoState>) -> impl IntoResponse {
    let base_url = state.site_config.base_url.trim_end_matches('/');
    let repository = DocumentRepository::new(state.pool.clone());

    // Fetch up to 50,000 public documents for the sitemap
    let documents = repository
        .list_all(Some(50_000), None)
        .await
        .unwrap_or_default();

    // Build the XML sitemap
    let now = chrono::Utc::now().to_rfc3339();
    let url_entries: String = documents
        .iter()
        .filter_map(|doc| {
            // Only include published/public documents
            if doc.status != "published" || doc.visibility != "public" {
                return None;
            }

            let slug = doc.slug.as_deref().unwrap_or(&doc.id);
            let loc = format!("{}/docs/{}", base_url, slug);
            let lastmod = doc.updated_at.to_rfc3339();

            Some(format!(
                r#"  <url>
    <loc>{}</loc>
    <lastmod>{}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>"#,
                loc, lastmod,
            ))
        })
        .collect::<Vec<_>>()
        .join("\n");

    let xml = format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>{base_url}/</loc>
    <lastmod>{now}</lastmod>
    <changefreq>daily</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>{base_url}/docs</loc>
    <lastmod>{now}</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>{base_url}/search</loc>
    <lastmod>{now}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>
{url_entries}
</urlset>"#,
        base_url = base_url,
        now = now,
        url_entries = url_entries,
    );

    (
        StatusCode::OK,
        [(header::CONTENT_TYPE, "application/xml; charset=utf-8")],
        xml,
    )
}

/// Server-side render a document page with full SEO metadata
///
/// Fetches the document from the database by ID, renders markdown to HTML,
/// and wraps it in the full-page ISR template with Open Graph, JSON-LD,
/// and canonical URL.
pub async fn serve_document_page(
    Path(document_id): Path<String>,
    State(state): State<SeoState>,
    Extension(nonce): Extension<crate::middleware::security_headers::CspNonce>,
) -> impl IntoResponse {
    let repository = DocumentRepository::new(state.pool.clone());

    // Parse the document ID from the path
    let doc_id = match document_id.parse::<DocumentId>() {
        Ok(id) => id,
        Err(_) => {
            return (
                StatusCode::NOT_FOUND,
                Html("<h1>404 — Document Not Found</h1>".to_string()),
            )
                .into_response();
        }
    };

    // Look up document by ID
    let metadata = match repository.get_by_id(&doc_id).await {
        Ok(doc) => doc,
        Err(_) => {
            return (
                StatusCode::NOT_FOUND,
                Html("<h1>404 — Document Not Found</h1>".to_string()),
            )
                .into_response();
        }
    };

    // Only serve published/public documents for SEO
    if metadata.status != "published" && metadata.visibility != "public" {
        return (
            StatusCode::NOT_FOUND,
            Html("<h1>404 — Document Not Found</h1>".to_string()),
        )
            .into_response();
    }

    // Render markdown to HTML
    let content = metadata.content.as_deref().unwrap_or("");
    let renderer = Renderer::new(RenderConfig::default());
    let html = match renderer.render(content, None) {
        Ok(result) => result.content,
        Err(_) => {
            // Fallback: return raw content wrapped in <pre>
            format!("<pre>{}</pre>", html_escape(content))
        }
    };

    // Parse tags
    let tags: Vec<String> = metadata.parse_tags().unwrap_or_default();

    // Build RenderContext
    let mut ctx = RenderContext::new(metadata.title.clone(), html);
    ctx.csp_nonce = Some(nonce.0.clone());
    ctx.author = Some(AuthorInfo {
        name: metadata.author_id.clone(),
        email: None,
        avatar_url: None,
    });
    ctx.metadata = Some(RenderMetadata {
        created_at: metadata.created_at.to_rfc3339(),
        updated_at: metadata.updated_at.to_rfc3339(),
        tags: tags.clone(),
        read_time: if metadata.word_count > 0 {
            Some((metadata.word_count as usize / 200).max(1))
        } else {
            None
        },
    });

    // Build site config for the renderer
    let site = RendererSiteConfig {
        site_title: state.site_config.title.clone(),
        site_description: state.site_config.description.clone(),
        base_url: state.site_config.base_url.clone(),
        theme_color: state.site_config.theme_color.clone(),
        og_image: state.site_config.og_image.clone(),
        template_dir: state.site_config.template_dir.clone(),
    };

    let full_html = render_full_page(&ctx, &site);

    Html(full_html).into_response()
}

/// Return a styled 404 page for unknown routes.
pub async fn not_found() -> impl IntoResponse {
    let html = r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>404 — Not Found | Tachyon</title>
    <script src="https://cdn.tailwindcss.com"><\/script>
    <style type="text/tailwindcss">
        @layer base { html { -webkit-font-smoothing: antialiased; } body { @apply bg-gray-50 text-gray-900 dark:bg-gray-900 dark:text-gray-100; margin: 0; } }
    <\/style>
</head>
<body>
    <div class="min-h-screen flex items-center justify-center">
        <div class="text-center">
            <p class="text-8xl font-bold text-blue-600 dark:text-blue-400">404</p>
            <h1 class="mt-4 text-2xl font-semibold text-gray-700 dark:text-gray-200">Page Not Found</h1>
            <p class="mt-2 text-gray-500 dark:text-gray-400">The page you're looking for doesn't exist or has been moved.</p>
            <a href="/" class="mt-6 inline-block px-5 py-2.5 bg-blue-600 text-white rounded-lg font-medium hover:bg-blue-700">Go Home</a>
        </div>
    </div>
</body>
</html>"#;
    (StatusCode::NOT_FOUND, Html(html.to_string())).into_response()
}

/// Return a styled 500 page for internal server errors.
pub async fn internal_error() -> impl IntoResponse {
    let html = r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>500 — Server Error | Tachyon</title>
    <script src="https://cdn.tailwindcss.com"><\/script>
    <style type="text/tailwindcss">
        @layer base { html { -webkit-font-smoothing: antialiased; } body { @apply bg-gray-50 text-gray-900 dark:bg-gray-900 dark:text-gray-100; margin: 0; } }
    <\/style>
</head>
<body>
    <div class="min-h-screen flex items-center justify-center">
        <div class="text-center">
            <p class="text-8xl font-bold text-red-600 dark:text-red-400">500</p>
            <h1 class="mt-4 text-2xl font-semibold text-gray-700 dark:text-gray-200">Internal Server Error</h1>
            <p class="mt-2 text-gray-500 dark:text-gray-400">Something went wrong. Please try again later.</p>
            <a href="/" class="mt-6 inline-block px-5 py-2.5 bg-blue-600 text-white rounded-lg font-medium hover:bg-blue-700">Go Home</a>
        </div>
    </div>
</body>
</html>"#;
    (StatusCode::INTERNAL_SERVER_ERROR, Html(html.to_string())).into_response()
}

/// Simple HTML escaping fallback
fn html_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            _ => out.push(c),
        }
    }
    out
}

/// Create the SEO router with robots.txt, sitemap.xml, and SSR document page
pub fn create_seo_router() -> axum::Router<SeoState> {
    use axum::routing::get;

    axum::Router::new()
        .route("/robots.txt", get(robots_txt))
        .route("/sitemap.xml", get(sitemap_xml))
        .route("/docs/{document_id}", get(serve_document_page))
        .fallback(not_found)
}
